# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_proj_3_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wtyczka_projekt_3DialogBase(object):
    def setupUi(self, wtyczka_projekt_3DialogBase):
        wtyczka_projekt_3DialogBase.setObjectName("wtyczka_projekt_3DialogBase")
        wtyczka_projekt_3DialogBase.resize(580, 340)
        font = QtGui.QFont()
        font.setPointSize(10)
        wtyczka_projekt_3DialogBase.setFont(font)
        self.groupBoxWarstwa = QtWidgets.QGroupBox(wtyczka_projekt_3DialogBase)
        self.groupBoxWarstwa.setGeometry(QtCore.QRect(20, 10, 260, 105))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxWarstwa.setFont(font)
        self.groupBoxWarstwa.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxWarstwa.setObjectName("groupBoxWarstwa")
        self.label = QtWidgets.QLabel(self.groupBoxWarstwa)
        self.label.setGeometry(QtCore.QRect(10, 25, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelAktywnaWarstwa = QtWidgets.QLabel(self.groupBoxWarstwa)
        self.labelAktywnaWarstwa.setGeometry(QtCore.QRect(10, 45, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAktywnaWarstwa.setFont(font)
        self.labelAktywnaWarstwa.setText("")
        self.labelAktywnaWarstwa.setObjectName("labelAktywnaWarstwa")
        self.pushButtonPokazAW = QtWidgets.QPushButton(self.groupBoxWarstwa)
        self.pushButtonPokazAW.setGeometry(QtCore.QRect(90, 75, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonPokazAW.setFont(font)
        self.pushButtonPokazAW.setObjectName("pushButtonPokazAW")
        self.groupBoxPunkty = QtWidgets.QGroupBox(wtyczka_projekt_3DialogBase)
        self.groupBoxPunkty.setGeometry(QtCore.QRect(300, 10, 260, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxPunkty.setFont(font)
        self.groupBoxPunkty.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxPunkty.setObjectName("groupBoxPunkty")
        self.label_2 = QtWidgets.QLabel(self.groupBoxPunkty)
        self.label_2.setGeometry(QtCore.QRect(10, 25, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelLiczbaPunkow = QtWidgets.QLabel(self.groupBoxPunkty)
        self.labelLiczbaPunkow.setGeometry(QtCore.QRect(180, 25, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLiczbaPunkow.setFont(font)
        self.labelLiczbaPunkow.setText("")
        self.labelLiczbaPunkow.setObjectName("labelLiczbaPunkow")
        self.pushButtonPokazP = QtWidgets.QPushButton(self.groupBoxPunkty)
        self.pushButtonPokazP.setGeometry(QtCore.QRect(90, 170, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonPokazP.setFont(font)
        self.pushButtonPokazP.setObjectName("pushButtonPokazP")
        self.textEdit = QtWidgets.QTextEdit(self.groupBoxPunkty)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 241, 95))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBoxPunkty)
        self.label_3.setGeometry(QtCore.QRect(10, 45, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBoxPolePowierzchni = QtWidgets.QGroupBox(wtyczka_projekt_3DialogBase)
        self.groupBoxPolePowierzchni.setGeometry(QtCore.QRect(20, 120, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxPolePowierzchni.setFont(font)
        self.groupBoxPolePowierzchni.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxPolePowierzchni.setObjectName("groupBoxPolePowierzchni")
        self.radioButtonm2 = QtWidgets.QRadioButton(self.groupBoxPolePowierzchni)
        self.radioButtonm2.setGeometry(QtCore.QRect(10, 30, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButtonm2.setFont(font)
        self.radioButtonm2.setChecked(True)
        self.radioButtonm2.setObjectName("radioButtonm2")
        self.radioButtona = QtWidgets.QRadioButton(self.groupBoxPolePowierzchni)
        self.radioButtona.setGeometry(QtCore.QRect(160, 60, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButtona.setFont(font)
        self.radioButtona.setObjectName("radioButtona")
        self.radioButtonkm2 = QtWidgets.QRadioButton(self.groupBoxPolePowierzchni)
        self.radioButtonkm2.setGeometry(QtCore.QRect(10, 60, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButtonkm2.setFont(font)
        self.radioButtonkm2.setObjectName("radioButtonkm2")
        self.radioButtonha = QtWidgets.QRadioButton(self.groupBoxPolePowierzchni)
        self.radioButtonha.setGeometry(QtCore.QRect(160, 30, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButtonha.setFont(font)
        self.radioButtonha.setObjectName("radioButtonha")
        self.pushButtonOblicz = QtWidgets.QPushButton(wtyczka_projekt_3DialogBase)
        self.pushButtonOblicz.setGeometry(QtCore.QRect(170, 300, 111, 31))
        self.pushButtonOblicz.setObjectName("pushButtonOblicz")
        self.pushButtonWyczysc = QtWidgets.QPushButton(wtyczka_projekt_3DialogBase)
        self.pushButtonWyczysc.setGeometry(QtCore.QRect(300, 300, 111, 31))
        self.pushButtonWyczysc.setObjectName("pushButtonWyczysc")
        self.groupBoxWyniki = QtWidgets.QGroupBox(wtyczka_projekt_3DialogBase)
        self.groupBoxWyniki.setGeometry(QtCore.QRect(90, 210, 400, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxWyniki.setFont(font)
        self.groupBoxWyniki.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxWyniki.setObjectName("groupBoxWyniki")
        self.labelOpisWyniku = QtWidgets.QLabel(self.groupBoxWyniki)
        self.labelOpisWyniku.setGeometry(QtCore.QRect(50, 25, 300, 20))
        self.labelOpisWyniku.setText("")
        self.labelOpisWyniku.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOpisWyniku.setObjectName("labelOpisWyniku")
        self.labelWynik = QtWidgets.QLabel(self.groupBoxWyniki)
        self.labelWynik.setGeometry(QtCore.QRect(50, 50, 300, 20))
        self.labelWynik.setText("")
        self.labelWynik.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWynik.setObjectName("labelWynik")

        self.retranslateUi(wtyczka_projekt_3DialogBase)
        QtCore.QMetaObject.connectSlotsByName(wtyczka_projekt_3DialogBase)

    def retranslateUi(self, wtyczka_projekt_3DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka_projekt_3DialogBase.setWindowTitle(_translate("wtyczka_projekt_3DialogBase", "Projekt 3"))
        self.groupBoxWarstwa.setTitle(_translate("wtyczka_projekt_3DialogBase", "Warstwa"))
        self.label.setText(_translate("wtyczka_projekt_3DialogBase", "Aktywna warstwa to:"))
        self.pushButtonPokazAW.setText(_translate("wtyczka_projekt_3DialogBase", "Pokaż"))
        self.groupBoxPunkty.setTitle(_translate("wtyczka_projekt_3DialogBase", "Punkty"))
        self.label_2.setText(_translate("wtyczka_projekt_3DialogBase", "Liczba wybranych punktów:"))
        self.pushButtonPokazP.setText(_translate("wtyczka_projekt_3DialogBase", "Pokaż"))
        self.label_3.setText(_translate("wtyczka_projekt_3DialogBase", "Współrzędne wybranuch punktów:"))
        self.groupBoxPolePowierzchni.setTitle(_translate("wtyczka_projekt_3DialogBase", "Jednostki pola powierzchni"))
        self.radioButtonm2.setText(_translate("wtyczka_projekt_3DialogBase", "Metry kwadratowe"))
        self.radioButtona.setText(_translate("wtyczka_projekt_3DialogBase", "Ary"))
        self.radioButtonkm2.setText(_translate("wtyczka_projekt_3DialogBase", "Kilometry kwadratowe"))
        self.radioButtonha.setText(_translate("wtyczka_projekt_3DialogBase", "Hektary"))
        self.pushButtonOblicz.setText(_translate("wtyczka_projekt_3DialogBase", "Oblicz"))
        self.pushButtonWyczysc.setText(_translate("wtyczka_projekt_3DialogBase", "Wyczuść"))
        self.groupBoxWyniki.setTitle(_translate("wtyczka_projekt_3DialogBase", "Wyniki"))

